USE [master]
GO

/****** Object:  Database [OaiPmhContext]    Script Date: 11.2.2014 12:51:46 ******/
CREATE DATABASE [OaiPmhContext]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'oaiPmh.mdf', FILENAME = N'C:\Users\Klemen\Documents\My Box Files\FederatedSearch\FederatedSearch\App_Data\oaiPmh.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'oaiPmh_log.ldf', FILENAME = N'C:\Users\Klemen\Documents\My Box Files\FederatedSearch\FederatedSearch\App_Data\oaiPmh_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OaiPmhContext] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OaiPmhContext].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OaiPmhContext] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OaiPmhContext] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OaiPmhContext] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OaiPmhContext] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OaiPmhContext] SET ARITHABORT OFF 
GO

ALTER DATABASE [OaiPmhContext] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [OaiPmhContext] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [OaiPmhContext] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OaiPmhContext] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OaiPmhContext] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OaiPmhContext] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OaiPmhContext] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OaiPmhContext] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OaiPmhContext] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OaiPmhContext] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OaiPmhContext] SET  ENABLE_BROKER 
GO

ALTER DATABASE [OaiPmhContext] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OaiPmhContext] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OaiPmhContext] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OaiPmhContext] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OaiPmhContext] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OaiPmhContext] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OaiPmhContext] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OaiPmhContext] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OaiPmhContext] SET  MULTI_USER 
GO

ALTER DATABASE [OaiPmhContext] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OaiPmhContext] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OaiPmhContext] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OaiPmhContext] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OaiPmhContext] SET  READ_WRITE 
GO

